baseURL = "https://devincody.github.io/BlogAether/"
languageCode = "en-us"
author="Devin Cody"
title = "Devin Cody"
description = "Engineering, science, and programming. More info to come."

theme="Aether"
paginate = 5
math = true
disqusShortname = "https-devincody-github-io-blog"
publishDir = "docs"
canonifyurls = true

[params]
brand = "The Blog"
bgimg = "https://www.tollivalerio.space/img/cream_pixels.png"
homeimg = "img/milkyway.webp"
siteFooter = "true"