baseURL = "https://devincody.github.io/Blog/"
languageCode = "en-us"
author="Devin Cody"
title = "Devin Cody"
description = "Engineering, science, and programming"
theme="Aether"
paginate = 5
math = true
disqusShortname = "https-devincody-github-io-blog"
publishDir = "docs"
canonifyurls = true
googleAnalytics = "G-YDQNJJN1GE"

[params]
brand = "The Blog"
bgimg = "img/cream_pixels.png"
homeimg = "img/milkyway.webp"
siteFooter = true
description = "Engineering, science, and programming"